---
name: debug
cpu: False
root_dir: "/home/mlelarge/EDF_Odilon/marc/data/logs"
path_dataset: "/home/mlelarge/EDF_Odilon/marc/data/" # Path where datasets are stored

train_data: # Train data related parameters
    num_workers: 16
    name_data: "sg_t16_train/" # "sg_t16_validation_final.npy"  #folder or file name (should end with .npy)
    name_weights: "sg_t16_train/"  # "sg_t16_validation_weights.npy" # 
    name_param: "sg_t16_train/preprocessing_params.pkl" #"preprocessing_params.pkl" # 
    n_slice: 9 #None

test_data: # Test data related parameters
    num_workers: 16
    num_batch_eval: 20
    name_data: "sg_t16_validation_final.npy"
    name_weights: "sg_t16_validation_weights.npy"
    
train: # Training parameters
    num_epochs: 10
    batch_size: 750
    prop_max_edges_given: 0.1
    print_freq: 500
    lr: !!float 5e-4
    scheduler_lr: True
    scheduler_step: 2
    f_output: "data/logs/debug/"

arch: # Architecture and model
    n_head: 4
    num_layers: 2
    embedding_dim : 240
    positional_encoding: True

observers:
    neptune:
        enable: No
        project: mlelarge/CAO
