experiment:
  dir: data/
logger:
  save_dir : 'experiment/results'
  name : 'gat_logs'

train_data: # Train data related parameters
  num_workers: 12
  file_data: "sg_test_final.npy" #folder or file name (should end with .npy)
  file_weights: "sg_test_weights.npy"  


val_data: # test data related parameters
    num_workers: 12
    num_batch_eval: 20
    file_data: "sg_test_final.npy"
    file_weights: "sg_test_weights.npy"
    coef_neg: 1.

train:
    cpu: False
    file_prep_parms: "preprocessing_params.pkl" #"preprocessing_params.pkl" # 
    batch_size: 128
    prop_max_edges_given: 0.1

optimizer:
    lr: !!float 5e-4
    scheduler_step: 2

model: # Architecture and model
    n_head: 4
    num_layers: 2
    embedding_dim : 240
    positional_encoding: True

