experiment:
  dir: data/

file_prep_parms: "preprocessing_params.pkl"
logger:
  save_dir : ''
  name : 'gat_logs'
  hparams_to_save: ['train', 'optimizer', 'model']

train_data: # Train data related parameters
  num_workers: 48
  file_data: "sg_merged_final_train.npy" #folder or file name (should end with .npy)
  file_weights: "sg_merged_weights_train.npy"
  prop_max_edges_given: 0.9
  variation: 0.25

val_data: # val data related parameters
  num_workers: 48
  file_data: "sg_merged_final_val.npy"
  prop_max_edges_given: 0.9
  variation: 0

test_data: # test data related parameters
  num_workers: 12
  file_data: "sg_merged_final_test.npy"
  prop_max_edges_given: 0.75
  variation: 0

train:
  batch_size: 4096
  max_epochs: 100

optimizer:
  lr: !!float 5e-4
  scheduler_step: 2
  coef_neg: 1.

model: # Architecture and model
  n_head: 4
  num_layers: 2
  embedding_dim : 240
  positional_encoding: True

