experiment:
  dir: /home/i37181/CAO_ML/git_depot/sketch_graph/modelrnn_gat/tests/asset/val

logger:
  save_dir : 'experiment/results'
  name : 'gat_logs'

train_data: # Train data related parameters
  num_workers: 1
  file_data: "sg_validation_final.npy" # "sg_t16_validation_final.npy"  #folder or file name (should end with .npy)
  file_weights: "sg_validation_weights.npy"  # "sg_t16_validation_weights.npy" # 
  n_slice: 9 #None

val_data: # Test data related parameters
    num_workers: 1
    num_batch_eval: 20
    file_data: "sg_validation_final.npy"
    file_weights: "sg_validation_weights.npy"
    coef_neg: 1.

train:
    cpu: False
    file_prep_parms: "preprocessing_params.pkl" #"preprocessing_params.pkl" # 
    batch_size: 8
    prop_max_edges_given: 0.1

optimizer:
    lr: !!float 5e-4
    scheduler_step: 2

model: # Architecture and model
    n_head: 4
    num_layers: 2
    embedding_dim : 240
    positional_encoding: True

